### Experiment configuration

## General settings
split: 'train' # data split; choices ['train', 'test']
debug: True
seed: 999
validation: True # use validation
use_hr: False # just for test

## Computational resources
accelerator: 'gpu'
devices: [0,] # indices of cuda devices to use

## Paths
dir_name: 'test'
data_dir: './data/UBnormal/'
exp_dir: './checkpoints'
test_path: './data/UBnormal/testing'
create_experiment_dir: True
load_ckpt: 'best_weights.ckpt'

## WANDB configuration
use_wandb: False
project_name: "project_name"
wandb_entity: "entity_name"
group_name: "group_name"
use_ema: False


##############################


### Model's configuration

## U-Net's configuration
device: 'cuda' # device to use; choices ['cuda', 'cpu']
embedding_dim: 16 # use latent_dim
dropout: 0 # probability of dropout
conditioning_strategy: 'inject' # choices ['inject' (add2layers), 'concat' (cat), 'inbetween_imp' (interleave), 'random_imp' (random_indices), 'no_condition' (none)]

## Conditioning network's configuration
conditioning_architecture: 'AE' # choices ['AE', 'E', 'E_unet']
conditioning_indices: [0,1,2] # indices to be used as condition. Don't pass -1, pass the actual last index instead. 
                              # If an int is given, it will be used as the number of random indices that will be selected
h_dim: 32 # dimension of the bottleneck at the end of the encoder
latent_dim: 16 # dimension of the latent space
channels: [32,16,32] # channels for the encoder

##############################


### Training's configuration

## Diffusion's configuration
noise_steps: 10 # how many diffusion steps to perform

### Optimizer and scheduler's configuration
n_epochs: 100
opt_lr: 0.001

## Losses' configuration
loss_fn: 'smooth_l1' # loss function; choices ['mse', 'l1', 'smooth_l1']
rec_weight: 0.01 # weight of the reconstruction loss

##############################


### Inference's configuration
n_generated_samples: 5 # number of samples to generate
model_return_value: 'loss'
aggregation_strategy: 'best'
save_tensors: True
load_tensors: True 
pad_size: -1 # size of the padding 


### Dataset's configuration

## Important parameters
dataset_choice: 'UBnormal'
seg_len: 6 # length of the window (cond+noised) 
vid_res: [1080,720]
batch_size: 1024

## Other parameters
headless: False
hip_center: False
kp18_format: False
normalization_strategy: 'robust' # use 'none' to avoid normalization, 'robust' otherwise
num_coords: 2
num_transform: 5
num_workers: 8
path_to_robust: './data/UBnormal/'
seg_stride: 1
seg_th: 0
start_offset: 0
symm_range: True
use_fitted_scaler: False